import '@/styles/global.scss';
import '@repo/ui/style.css';
import clsx from 'clsx';
import type { Metadata } from 'next';

import { Bottom } from '@/components/basic/Bottom';
import { Header } from '@/components/basic/Header';
import ClientContext from '@/context/ClientContext';
import { notoSansKr, notoSerifFont, pretendardFont } from '@/styles/fonts';
import { getUserServerSession } from '@/utils/session/getUserServerSession';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const { session } = await getUserServerSession();
  return (
    <html
      lang="ko"
      className={clsx(
        pretendardFont.variable,
        notoSerifFont.variable,
        notoSansKr.variable
      )}
    >
      <body>
        <ClientContext session={session}>
          <div className={'container content-padding'}>
            <Header />
            {children}
            <Bottom />
            <div id="modal-root" />
          </div>
        </ClientContext>
      </body>
    </html>
  );
};

export default RootLayout;
