import '@/styles/global.scss';
import '@repo/ui/style.css';
import clsx from 'clsx';
import type { Metadata } from 'next';

import ClientContext from '@/context/ClientContext';
import { notoSansKr, notoSerifFont, pretendardFont } from '@/styles/fonts';
import { getUserServerSession } from '@/utils/session/getUserServerSession';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const { session } = await getUserServerSession();
  return (
    <html
      lang="ko"
      className={clsx(
        pretendardFont.variable,
        notoSerifFont.variable,
        notoSansKr.variable
      )}
    >
      <body>
        <ClientContext session={session}>
          {children}
          <div id="modal-root" />
        </ClientContext>
      </body>
    </html>
  );
};

export default RootLayout;
