import '@/styles/global.scss';
import '@repo/ui/style.css';
import clsx from 'clsx';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import { Footer } from '@/components/basic/Footer';
import { Header } from '@/components/basic/Header';
import ClientContext from '@/context/ClientContext';
import { notoSansKr, notoSerifFont, pretendardFont } from '@/styles/fonts';
import { getUserServerSession } from '@/utils/session/getUserServerSession';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) => {
  const { session } = await getUserServerSession();
  const messages = await getMessages();
  return (
    <html
      lang={lang}
      className={clsx(
        pretendardFont.variable,
        notoSerifFont.variable,
        notoSansKr.variable
      )}
    >
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ClientContext session={session}>
            <div className={'container content-padding'}>
              <Header />
              <main>{children}</main>
              <Footer />
              <div id="modal-root" />
            </div>
          </ClientContext>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
