/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { AccomplishmentData } from './accomplishmentData';
import type { Error } from './error';

export interface ApiResponseAccomplishmentData {
  data?: AccomplishmentData;
  error?: Error;
  success: boolean;
}
