/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { ReleaseData } from './releaseData';
import type { Error } from './error';

export interface ApiResponseListReleaseData {
  data?: ReleaseData[];
  error?: Error;
  success: boolean;
}
