/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { ProjectLikeResponse } from './projectLikeResponse';
import type { Error } from './error';

export interface ApiResponseProjectLikeResponse {
  data?: ProjectLikeResponse;
  error?: Error;
  success: boolean;
}
