/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */

export type CarouselMediaMediaType =
  (typeof CarouselMediaMediaType)[keyof typeof CarouselMediaMediaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CarouselMediaMediaType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
} as const;
