/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { ErrorProperties } from './errorProperties';

export interface Error {
  code: string;
  message?: string;
  properties: ErrorProperties;
}
