/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { GetProjectListCategory } from './getProjectListCategory';

export type GetProjectListParams = {
  /**
   * Zero-based page index (0..N)
   */
  page?: number;
  /**
   * The size of the page to be returned
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[];
  /**
   * 조회 할 카테고리(Null 시 모든 카테고리 조회)
   */
  category?: GetProjectListCategory;
};
