/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { UserLink } from './userLink';

export interface MemberProfile {
  links: UserLink[];
  username: string;
  userPicture: string;
  userRole: string[];
}
