/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */

export type ProjectPhase = (typeof ProjectPhase)[keyof typeof ProjectPhase];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectPhase = {
  PHASE_0: 'PHASE_0',
  PHASE_1: 'PHASE_1',
  PHASE_2: 'PHASE_2',
  PHASE_3: 'PHASE_3',
  PHASE_4: 'PHASE_4',
  PHASE_5: 'PHASE_5',
} as const;
