/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { ProjectDataCategoriesItem } from './projectDataCategoriesItem';
import type { ProjectLink } from './projectLink';
import type { CarouselMedia } from './carouselMedia';

export interface ProjectData {
  banner?: string;
  brandColor?: string;
  categories: ProjectDataCategoriesItem[];
  content: string;
  createdAt: string;
  id: number;
  likeCount: number;
  links: ProjectLink[];
  projectMedia: CarouselMedia[];
  status: string;
  subscribeCount: number;
  subTitle?: string;
  summary?: string;
  thumbnail?: string;
  title: string;
  updatedAt: string;
  viewCount: number;
}
