/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */

/**
 * 프로젝트 링크 수정 요청 DTO
 */
export interface ProjectLinkUpdateRequest {
  links: string[];
}
