/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { ProjectMetadataRequestCategoriesItem } from './projectMetadataRequestCategoriesItem';

/**
 * 프로젝트 메타데이터 수정 요청 DTO
 */
export interface ProjectMetadataRequest {
  banner?: Blob;
  /** 프로젝트 상세 설명 */
  brandColor: string;
  /** 프로젝트 카테고리 */
  categories: ProjectMetadataRequestCategoriesItem[];
  /** 프로젝트 상태 0~5 */
  phase: number;
  /** 프로젝트 슬러그 (URL) 비어있을 시 title을 활용하여 자동 생성 */
  slug?: string;
  /** 프로젝트 요약 */
  subTitle: string;
  /** 프로젝트 짧은 설명 */
  summary: string;
  thumbnail?: Blob;
  /** 프로젝트 제목 */
  title: string;
}
