/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { ProjectSummaryCategoryItem } from './projectSummaryCategoryItem';

export interface ProjectSummary {
  awardCount: number;
  category: ProjectSummaryCategoryItem[];
  createdAt?: string;
  id: number;
  likeCount: number;
  memberCount: number;
  subTitle?: string;
  thumbnail?: string;
  title: string;
  viewCount: number;
}
