/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { ProjectBadge } from './projectBadge';
import type { CarouselMedia } from './carouselMedia';
import type { ProjectCategoriesItem } from './projectCategoriesItem';
import type { ProjectLink } from './projectLink';
import type { ProjectMaker } from './projectMaker';
import type { ProjectPhase } from './projectPhase';
import type { ProjectReleasePress } from './projectReleasePress';
import type { ProjectRelease } from './projectRelease';
import type { ProjectStatus } from './projectStatus';
import type { ProjectSubscribe } from './projectSubscribe';

export interface Project {
  accomplishmentText?: string;
  authorId: number;
  badges: ProjectBadge[];
  banner?: string;
  brandColor?: string;
  carouselMedias: CarouselMedia[];
  categories: ProjectCategoriesItem[];
  content: string;
  createdAt: string;
  id: number;
  likeCount: number;
  links: ProjectLink[];
  makers: ProjectMaker[];
  phase?: ProjectPhase;
  pressReleases: ProjectReleasePress[];
  release?: ProjectRelease[];
  releaseReleases?: ProjectReleasePress[];
  releases: ProjectRelease[];
  slug: string;
  status: ProjectStatus;
  subscribeCount: number;
  subscribers: ProjectSubscribe[];
  subTitle?: string;
  summary?: string;
  teamGoal?: string;
  thumbnail?: string;
  title: string;
  updatedAt: string;
  viewCount: number;
}
