/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */

export type ProjectLinkType =
  (typeof ProjectLinkType)[keyof typeof ProjectLinkType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectLinkType = {
  INSTAGRAM: 'INSTAGRAM',
  NOTION: 'NOTION',
  GITHUB: 'GITHUB',
  GOOGLE_PLAY: 'GOOGLE_PLAY',
  APP_STORE: 'APP_STORE',
  YOUTUBE: 'YOUTUBE',
  WEBSITE: 'WEBSITE',
  ETC: 'ETC',
} as const;
