/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */

/**
 * 프로젝트 카테고리
 */
export type ProjectMetadataRequestCategoriesItem =
  (typeof ProjectMetadataRequestCategoriesItem)[keyof typeof ProjectMetadataRequestCategoriesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectMetadataRequestCategoriesItem = {
  AI: 'AI',
  HEALTHCARE: 'HEALTHCARE',
  SOCIAL_EFFECT: 'SOCIAL_EFFECT',
  EDUCATION: 'EDUCATION',
  TRAVEL: 'TRAVEL',
} as const;
