/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { ProjectPageDataCategory } from './projectPageDataCategory';
import type { ProjectSummary } from './projectSummary';

export interface ProjectPageData {
  category?: ProjectPageDataCategory;
  projects: ProjectSummary[];
  totalMembers: number;
  totalProjects: number;
}
