/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */

export interface ProjectBadge {
  awardDate: string;
  awardDetails: string;
  awardName: string;
  imageUrl: string;
  issuingOrganization: string;
  order: number;
}
