/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */
import type { UserLinkResponse } from './userLinkResponse';
import type { UserNotificationResponse } from './userNotificationResponse';

export interface UserResponse {
  email: string;
  enabled: boolean;
  links: UserLinkResponse[];
  name?: string;
  nickname?: string;
  notifications: UserNotificationResponse[];
  phone?: string;
  profileImageUrl?: string;
  userId: number;
}
