/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * PhaseOn API
 * 페이즈온 API 문서
 * OpenAPI spec version: v1
 */

export type UserLinkLinkType =
  (typeof UserLinkLinkType)[keyof typeof UserLinkLinkType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserLinkLinkType = {
  GITHUB: 'GITHUB',
  LINKEDIN: 'LINKEDIN',
  TWITTER: 'TWITTER',
  FACEBOOK: 'FACEBOOK',
  INSTAGRAM: 'INSTAGRAM',
  YOUTUBE: 'YOUTUBE',
  BLOG: 'BLOG',
  WEBSITE: 'WEBSITE',
  OTHER: 'OTHER',
} as const;
